name: Checkmarx One Escanear

on:
  push:
    branches:
      - principal
      - maestro
      - desarrollo
  pull_request:
    branches:
      - principal
      - maestro
      - desarrollo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkmarx-One-Scan
        uses: checkmarx/ast-github-action@main
        with:
          project_name: 'EmmanuelTobonKMH/juice-shop'
          cx_tenant: 'nfr_lugapel-ast'
          base_uri: 'https://ast.checkmarx.net/'
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          branch: ${{ github.ref_name }}



      
